name: Package NPM

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build:lib
    - run: npm run pack
    - run: npm publish dist/ngx-gauge
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    
